server:
  port: 8080

spring:
  application:
    name: debezium-sync-service
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=cdc;encrypt=false;trustServerCertificate=true;
    username: sa
    password: MssqlPassword123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: mssql-cdc-sync-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: false
    listener:
      ack-mode: MANUAL_IMMEDIATE
      concurrency: 1

cdc:
  topic: cdc.events
  dlt-topic: cdc.events-dlt
  retry:
    max-attempts: 3
    backoff-interval-ms: 2000