{
  "connect.name": "dbz.ref.regions.Value",
  "fields": [
    {
      "name": "id",
      "type": "int"
    },
    {
      "name": "code",
      "type": "string"
    },
    {
      "name": "name",
      "type": "string"
    },
    {
      "name": "currency_code",
      "type": "string"
    },
    {
      "default": null,
      "name": "__deleted",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "default": null,
      "name": "__op",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "default": null,
      "name": "__table",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "default": null,
      "name": "__schema",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "default": null,
      "name": "__lsn",
      "type": [
        "null",
        "long"
      ]
    },
    {
      "default": null,
      "name": "__txId",
      "type": [
        "null",
        "long"
      ]
    },
    {
      "default": null,
      "name": "__ts_ms",
      "type": [
        "null",
        "long"
      ]
    }
  ],
  "name": "Value",
  "namespace": "dbz.ref.regions",
  "type": "record"
}
