{
  "connect.name": "dbz.sales.customers.Value",
  "fields": [
    {
      "default": 0,
      "name": "id",
      "type": {
        "connect.default": 0,
        "type": "long"
      }
    },
    {
      "name": "email",
      "type": "string"
    },
    {
      "name": "name",
      "type": "string"
    },
    {
      "name": "region_id",
      "type": "int"
    },
    {
      "default": "1970-01-01T00:00:00.000000Z",
      "name": "created_at",
      "type": {
        "connect.default": "1970-01-01T00:00:00.000000Z",
        "connect.name": "io.debezium.time.ZonedTimestamp",
        "connect.version": 1,
        "type": "string"
      }
    },
    {
      "default": null,
      "name": "__deleted",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "default": null,
      "name": "__op",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "default": null,
      "name": "__table",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "default": null,
      "name": "__schema",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "default": null,
      "name": "__lsn",
      "type": [
        "null",
        "long"
      ]
    },
    {
      "default": null,
      "name": "__txId",
      "type": [
        "null",
        "long"
      ]
    },
    {
      "default": null,
      "name": "__ts_ms",
      "type": [
        "null",
        "long"
      ]
    }
  ],
  "name": "Value",
  "namespace": "dbz.sales.customers",
  "type": "record"
}
